/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1beta1

import (
	pager_v1beta1 "github.com/munnerz/k8s-api-pager-demo/pkg/apis/pager/v1beta1"
	versioned "github.com/munnerz/k8s-api-pager-demo/pkg/client/clientset/versioned"
	internalinterfaces "github.com/munnerz/k8s-api-pager-demo/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/munnerz/k8s-api-pager-demo/pkg/client/listers/pager/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// AlertInformer provides access to a shared informer and lister for
// Alerts.
type AlertInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.AlertLister
}

type alertInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlertInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PagerV1beta1().Alerts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PagerV1beta1().Alerts(namespace).Watch(options)
			},
		},
		&pager_v1beta1.Alert{},
		resyncPeriod,
		indexers,
	)
}

func (f *alertInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlertInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alertInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pager_v1beta1.Alert{}, f.defaultInformer)
}

func (f *alertInformer) Lister() v1beta1.AlertLister {
	return v1beta1.NewAlertLister(f.Informer().GetIndexer())
}
