/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This package is generated by client-gen with custom arguments.

// Package fake has the automatically generated clients.
package fake
