/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	pager_v1alpha1 "github.com/munnerz/k8s-api-pager-demo/pkg/apis/pager/v1alpha1"
	client "github.com/munnerz/k8s-api-pager-demo/pkg/client"
	internalinterfaces "github.com/munnerz/k8s-api-pager-demo/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/munnerz/k8s-api-pager-demo/pkg/listers/pager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// AlertInformer provides access to a shared informer and lister for
// Alerts.
type AlertInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AlertLister
}

type alertInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

func newAlertInformer(client client.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	sharedIndexInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.PagerV1alpha1().Alerts(v1.NamespaceAll).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.PagerV1alpha1().Alerts(v1.NamespaceAll).Watch(options)
			},
		},
		&pager_v1alpha1.Alert{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)

	return sharedIndexInformer
}

func (f *alertInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pager_v1alpha1.Alert{}, newAlertInformer)
}

func (f *alertInformer) Lister() v1alpha1.AlertLister {
	return v1alpha1.NewAlertLister(f.Informer().GetIndexer())
}
