/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This file was automatically generated by lister-gen

package v1alpha1

// TestListerExpansion allows custom methods to be added to
// TestLister.
type TestListerExpansion interface{}

// TestNamespaceListerExpansion allows custom methods to be added to
// TestNamespaceLister.
type TestNamespaceListerExpansion interface{}

// TestRunListerExpansion allows custom methods to be added to
// TestRunLister.
type TestRunListerExpansion interface{}

// TestRunNamespaceListerExpansion allows custom methods to be added to
// TestRunNamespaceLister.
type TestRunNamespaceListerExpansion interface{}
