/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/srossross/k8s-test-controller/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Tests returns a TestInformer.
	Tests() TestInformer
	// TestRuns returns a TestRunInformer.
	TestRuns() TestRunInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// Tests returns a TestInformer.
func (v *version) Tests() TestInformer {
	return &testInformer{factory: v.SharedInformerFactory}
}

// TestRuns returns a TestRunInformer.
func (v *version) TestRuns() TestRunInformer {
	return &testRunInformer{factory: v.SharedInformerFactory}
}
